/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OrganizationSlugBookingFormSlugRouteImport } from './routes/$organizationSlug.$bookingFormSlug'

const OrganizationSlugBookingFormSlugRoute =
  OrganizationSlugBookingFormSlugRouteImport.update({
    id: '/$organizationSlug/$bookingFormSlug',
    path: '/$organizationSlug/$bookingFormSlug',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/$organizationSlug/$bookingFormSlug': typeof OrganizationSlugBookingFormSlugRoute
}
export interface FileRoutesByTo {
  '/$organizationSlug/$bookingFormSlug': typeof OrganizationSlugBookingFormSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$organizationSlug/$bookingFormSlug': typeof OrganizationSlugBookingFormSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/$organizationSlug/$bookingFormSlug'
  fileRoutesByTo: FileRoutesByTo
  to: '/$organizationSlug/$bookingFormSlug'
  id: '__root__' | '/$organizationSlug/$bookingFormSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  OrganizationSlugBookingFormSlugRoute: typeof OrganizationSlugBookingFormSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$organizationSlug/$bookingFormSlug': {
      id: '/$organizationSlug/$bookingFormSlug'
      path: '/$organizationSlug/$bookingFormSlug'
      fullPath: '/$organizationSlug/$bookingFormSlug'
      preLoaderRoute: typeof OrganizationSlugBookingFormSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  OrganizationSlugBookingFormSlugRoute: OrganizationSlugBookingFormSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
